### PR TITLE
re-factor -X options

### PR DESCRIPTION
**Pull request by Schmell**
This change replaces redunant -X option code and adds addXdetails function to handle it. it reduces the number of lines and is a little cleaner.
code also includes extra details even if there is no description (replaces description with title for looks) and adds season and episode numbers to extra details. Also added date and time to generator just to help with tracking changes while testing.

### CODE REVIEW

**Comment by edit4ever** [comment]
Thanks - I'm not that familiar with python - so I appreciate the improvements.  What I would like to do is move this to a new branch.  As the way extra details are displayed is a personal preference, my goal is to build out a new options page in kodi to turn on and off the different xtra details elements.  That way if you use a skin that already shows season/episode next to the plot description - it won't be redundent for you.  Or in your example of title being put in the description, that would put 2 titles next to each other in the skin that I use.

The generator change is a good idea that should be in both branches.

**Comment by Schmell** [comment]
Ah yes. Skins can be complicated. What skin are you using?

**Comment by edit4ever** [comment]
I have customized Eminence 2.0 (especially the epg) - my updates are posted on the kodi skin support forum.  However, in working in the skins and the xmltv files for tvheadend, I realized that everyone will likely use a different display, so the ability to customized what is added to the "plot" description would be great.  Unfortunately, my attention has been focused on developing ATSC DVB support in the kernel used by amlogic devices.  I'm trying to build an affordable two tuner dvr based on the KII Pro.

**Comment by Schmell** [comment]
Sounds cool. I'll check it out.
A new branch sounds good and I'll see if I can refactor more and make some
stuff cleaner and more efficient.

**Comment by edit4ever** [comment]
Check out the branch update - I think I "sorted" the basics of the new xtra details sorting functions.

I need a little help with the credits part - as the way the credits pull and sort is a little messy and isn't working in the separate def addXDetails section.

Let me know if you get a chance to test this - then I can release it for others to test.

**Pull request closed without merging**
